# Generated by Django 4.2.8 on 2026-01-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='renovation_level',
            field=models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('plus', 'Plus'), ('premium', 'Premium')], default='none', max_length=20),
        ),
    ]
